In [1]:
#;.pykx.disableJupyter()

In [2]:
# https://code.kx.com/pykx/3.0/examples/jupyter-integration.html#q-first-mode
import pykx as kx
kx.util.jupyter_qfirst_enable()

PyKX now running in 'jupyter_qfirst' mode. All cells by default will be run as q code. 
Include '%%py' at the beginning of each cell to run as python code. 


# Kx Training: Exercise - Tables

## Creating tables and investigation

### Unkeyed Tables

* Create a table called `quote` with columns
        - sym:`IBM.L`VOD.L`VED.L
        - price:50.3 12.1 151.56
        - size: 1000 200 60

In [ ]:
quote:([]sym:`IBM.L`VOD.L`VED.L;price:50.3 12.1 151.56;size: 1000 200 60)
quote

In [5]:
quote:([] sym:`IBM.L`VOD.L`VED.L; price:50.3 12.1 151.56; size:1000 200 60)

* How can we return the number of rows in this table?

In [ ]:
count quote

In [6]:
count quote

3


* What is the type of the table?

In [ ]:
type quote

In [7]:
type quote

98h


* What command can we use to see the data types of each column of the table?

In [ ]:
meta quote

In [8]:
meta quote

c    | t f a
-----| -----
sym  | s    
price| f    
size | j    


### Keyed Tables

* Create a keyed table `tradeKey` with the following data:


    - id:1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 (key)
    - sym:`IBM`GE`JPM`BP`JPM`BP`JPM`ASD`JPM`IBM
    - price:79 88 83 74 87 54 95 91 52 89
    - size:117 123 112 166 136 137 144 128 120 130
    - side:`B`S`B`S`B`S`B`B`S`B

Keyed on `id`. Do so using the following methods:

- Dictionary of flipped dictionaries (aka tables)
- Table definition syntax

In [ ]:
// Dictionary of flipped dictionaries
k:flip (enlist `id)!enlist 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010
v:flip `sym`price`size`side!(`IBM`GE`JPM`BP`JPM`BP`JPM`ASD`JPM`IBM;
                             79 88 83 74 87 54 95 91 52 89;
                             117 123 112 166 136 137 144 128 120 130;
                             `B`S`B`S`B`S`B`B`S`B)
show tradeKey:k!v

In [ ]:
// Table definition syntax
tradeKey:([id:1001 1002 1003 1004 1005 1006 1007 1008 1009 1010]
        sym:`IBM`GE`JPM`BP`JPM`BP`JPM`ASD`JPM`IBM;
        price:iq:79 88 83 74 87 54 95 91 52 89;
        size:117 123 112 166 136 137 144 128 120 130;
        side:`B`S`B`S`B`S`B`B`S`B)

show tradeKey

In [24]:
// by table definition
tradeKey1:([id:1001 1002 1003 1004 1005 1006 1007 1008 1009 1010] sym:`IBM`GE`JPM`BP`JPM`BP`JPM`ASD`JPM`IBM;price:79 88 83 74 87 54 95 91 52 89; size:117 123 112 166 136 137 144 128 120 130; side:`B`S`B`S`B`S`B`B`S`B)

// by dictionary of two dictionaries
ks:flip (enlist `id)!enlist 1001 1002 1003 1004 1005 1006 1007 1008 1009 1010;
vals:flip `sym`price`size`side!(`IBM`GE`JPM`BP`JPM`BP`JPM`ASD`JPM`IBM;79 88 83 74 87 54 95 91 52 89;117 123 112 166 136 137 144 128 120 130;`B`S`B`S`B`S`B`B`S`B)
tradeKey:tradeKey2:ks!vals

tradeKey1 ~ tradeKey2

1b


* Confirm that `tradeKey` is a keyed table

In [ ]:
99h~type tradeKey

In [26]:
type tradeKey / dict 99
type key tradeKey / table 98
type value tradeKey / table 98

99h
98h
98h


* Extract the keys from the trade table


In [ ]:
key tradeKey

In [29]:
key tradeKey
(key tradeKey)[`id]
exec id from tradeKey

id  
----
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1001 1002 1003 1004 1005 1006 1007 1008 1009 1010
1001 1002 1003 1004 1005 1006 1007 1008 1009 1010


* Extract the values of the trade table

In [ ]:
value tradeKey

In [30]:
value tradeKey

sym price size side
-------------------
IBM 79    117  B   
GE  88    123  S   
JPM 83    112  B   
BP  74    166  S   
JPM 87    136  B   
BP  54    137  S   
JPM 95    144  B   
ASD 91    128  B   
JPM 52    120  S   
IBM 89    130  B   


## Manipulating tables

### Unkeyed Tables

* Return the `quote` table as a dictionary.

In [ ]:
flip quote

In [31]:
flip quote

sym  | IBM.L VOD.L VED.L 
price| 50.3  12.1  151.56
size | 1000  200   60    


* Use dictionary syntax to return the prices of the `quote` table as a list.

In [ ]:
quote `price
quote[`price]

In [35]:
quote[`price]

50.3 12.1 151.56


* Use dot syntax to return the sym column as a list.

In [ ]:
quote.sym

In [36]:
quote.sym

`IBM.L`VOD.L`VED.L


* Rename the first two columns of the table to SYM and PRICE

In [ ]:
`SYM`PRICE xcol quote

In [39]:
`SYM`PRICE xcol quote

SYM   PRICE  size
-----------------
IBM.L 50.3   1000
VOD.L 12.1   200 
VED.L 151.56 60  


* Order the table descending by size

In [ ]:
`size xdesc quote

In [40]:
`size xdesc quote

sym   price  size
-----------------
IBM.L 50.3   1000
VOD.L 12.1   200 
VED.L 151.56 60  


* Reorder the columns so that price and size are the other way round.

In [ ]:
`sym`size`price xcols quote  //if you're getting confused between xcol and xcols, it may be helpful to think 
                                //xcols has an (s) for re-Sorting

In [47]:
`sym`size`price xcols quote

sym   size price 
-----------------
IBM.L 1000 50.3  
VOD.L 200  12.1  
VED.L 60   151.56


Consider the two following tables:

  
  `` t3:([] sym:`a`b`c`d; price:1 2 3 4f;size:100 200 300 400)
t4:([] sym:`a`c`f; price:11 3 11f;size:100 300 1000)``
    
* Retrieve the rows where t3 and t4 are the same

In [ ]:
show t3:([] sym:`a`b`c`d; price:1 2 3 4f;size:100 200 300 400)
show t4:([] sym:`a`c`f; price:11 3 11f;size:100 300 1000)
t3 where t3 in t4  

In [ ]:
t3 inter t4   //finding the intersection will also work

In [53]:
t3:([] sym:`a`b`c`d; price:1 2 3 4f;size:100 200 300 400)
t4:([] sym:`a`c`f; price:11 3 11f;size:100 300 1000)

t3 inter t4
t3 where t3 in t4 // t3[2], where t3 in t4 returns index 2

sym price size
--------------
c   3     300 
sym price size
--------------
c   3     300 


* Retrieve the row indices of t3 which are in t4

In [ ]:
where t3 in t4

In [54]:
where t3 in t4

,2


* Retrieve the union set of t3 and t4

In [ ]:
t3 union t4

In [59]:
t3 union t4

sym price size
--------------
a   1     100 
b   2     200 
c   3     300 
d   4     400 
a   11    100 
f   11    1000


* Retrieve the rows in t3, except for the ones in t4

In [ ]:
t3 except t4

In [64]:
(t3 where not t3 in t4) ~ t3 except t4
t3 except t4

1b
sym price size
--------------
a   1     100 
b   2     200 
d   4     400 


### Keyed Tables

* Extract the values of the sym column from the `tradeKey` table

In [ ]:
(value tradeKey)[`sym]

In [66]:
tradeKey

exec sym from tradeKey
(value tradeKey)[`sym]

id  | sym price size side
----| -------------------
1001| IBM 79    117  B   
1002| GE  88    123  S   
1003| JPM 83    112  B   
1004| BP  74    166  S   
1005| JPM 87    136  B   
1006| BP  54    137  S   
1007| JPM 95    144  B   
1008| ASD 91    128  B   
1009| JPM 52    120  S   
1010| IBM 89    130  B   
`IBM`GE`JPM`BP`JPM`BP`JPM`ASD`JPM`IBM
`IBM`GE`JPM`BP`JPM`BP`JPM`ASD`JPM`IBM


* Extract the row values (sym, price, size and side) for id `1005` and `1008` from the `tradeKey` table

In [ ]:
tradeKey[([]id:1005 1008)]

In [67]:
tradeKey[([] id:(1005;1008))]

sym price size side
-------------------
JPM 87    136  B   
ASD 91    128  B   


* Extract the price value for `tradeKey` id `1002`

In [69]:
tradeKey[([]id:enlist 1002);`price]

,88


In [68]:
tradeKey[1002;`price]

88


* Modify the side for `tradeKey` id `1009` to be `` `B``

In [ ]:
tradeKey[([]id:enlist 1009);`side]:enlist `B
show tradeKey

In [72]:
tradeKey[([]id:enlist 1009);`side]:`B
tradeKey

id  | sym price size side
----| -------------------
1001| IBM 79    117  B   
1002| GE  88    123  S   
1003| JPM 83    112  B   
1004| BP  74    166  S   
1005| JPM 87    136  B   
1006| BP  54    137  S   
1007| JPM 95    144  B   
1008| ASD 91    128  B   
1009| JPM 52    120  B   
1010| IBM 89    130  B   


* Unkey the `tradeKey` table and assign it to the variable `unkeyedTrade`

In [ ]:
unkeyedTrade:0!tradeKey
//or
unkeyedTrade:() xkey tradeKey
show unkeyedTrade

In [73]:
unkeyedTrade:0!tradeKey

## Appending records to tables

### Unkeyed Tables

* Create the table 

```t1:([] sym:`a`b`c`d`c`d; price:1 2 3 4 8 9f)```

Use the insert syntax to insert the symbols <code>\`e</code> and <code>\`g</code> and the prices 5 and 7. Do it as a bulk insert.

In [ ]:
show t1:([] sym:`a`b`c`d`c`d; price:1 2 3 4 3 4f)
`t1 insert (`e`g;5 7f)
t1

In [ ]:
//alternatively as a table insert: 
`t1 insert ([]sym:`e`g; price:5 7f)

In [75]:
t1:([] sym:`a`b`c`d`c`d; price:1 2 3 4 8 9f)
`t1 insert ([] sym:`e`g; price:5 7f)

6 7


* Use the join (,) syntax to do the same thing

In [ ]:
t1:([] sym:`a`b`c`d`c`d; price:1 2 3 4 3 4f)     
show t1,:([]sym:`e`g;price:5 7f)          //join and amend in place 
meta t1 

In [76]:
`t1, ([] sym:`e`g; price:5 7f)

`t1
`sym`price!(`e;5f)
`sym`price!(`g;7f)


* Extract the 3rd row from t1. What is it's type?

In [79]:
t1 2
type t1 2 

sym  | `c
price| 3f
99h


In [80]:
t1 2
type t1 2

sym  | `c
price| 3f
99h


* Extract the distinct items from t1

In [ ]:
t1 
distinct t1  //will return a table of the distinct rows in our data

In [82]:
distinct t1

sym price
---------
a   1    
b   2    
c   3    
d   4    
c   8    
d   9    
e   5    
g   7    


* Using the distinct items from `t1` as defined above, create `t2` which is `t1` with an additional column, size. Size should be of type int and can be calculated as `100*1+(index in list)`

In [ ]:
show t2: distinct t1
t2[`size]: `int$100*1+til count distinct t1
meta t2
t2

In [87]:
t2:distinct t1
t2[`size]:`int$100*1+til count t2
t2

sym price size
--------------
a   1     100 
b   2     200 
c   3     300 
d   4     400 
c   8     500 
d   9     600 
e   5     700 
g   7     800 


* Run the code:

    <code>t2 upsert flip (\`a\`g;1 2;3 5)</code>
    
    Why does it fail?

The numbers in the new rows are longs by default, size and price columns are int and float

In [89]:
flip (`a`g;1 2; 3 5)             //we are using flip here to format the data as rows
t2 upsert flip (`a`g;1 2; 3 5)   //we get a type error 

`a 1 3
`g 2 5


QError: type

In [90]:
//first step - check our types! 
show tabTypes:0!meta t2                           //unkeying so we can add a new column using dictionary notation
tabTypes[`newDataTypes]:type each (`a`g;1 2; 3 5) //checking the type of each of our new data
tabTypes                                          //can see a disagreement between the type of size

c     t f a newDataTypes
------------------------
sym   s     11          
price f     7           
size  i     7           
c     t f a
-----------
sym   s    
price f    
size  i    


-6 -6h


* Correct the code so that it works without an error.

In [ ]:
t2 upsert flip (`a`g;1 2f;3 5)

In [98]:
t2 upsert flip (`a`g;1 2f;`int$3 5)

sym price size
--------------
a   1     100 
b   2     200 
c   3     300 
d   4     400 
c   8     500 
d   9     600 
e   5     700 
g   7     800 
a   1     3   
g   2     5   


### Keyed Tables

* Add the following new rows to the keyed `tradeKey` table


    id   | sym   price   size     side
    -----| -----------------------------
    1011 | `BP    81      111     `B
    1012 | `JPM   65      156     `B

In [ ]:
`tradeKey insert flip `id`sym`price`size`side!(1011 1012;`BP`JPM;81 65;111 156;`B`B)
//or 
`tradeKey upsert flip `id`sym`price`size`side!(1011 1012;`BP`JPM;81 65;111 156;`B`B)

In [117]:
tradeKey upsert ([] id:1011 1012; sym:`BP`JPM; price:81 65; size:111 156; side:`B`B)
tradeKey upsert flip `id`sym`price`size`side!(1011 1012;`BP`JPM;81 65;111 156;`B`B )
`tradeKey insert ([] id:1011 1012; sym:`BP`JPM; price:81 65; size:111 156; side:`B`B)
tradeKey

id  | sym price size side
----| -------------------
1001| IBM 79    117  B   
1002| GE  88    123  S   
1003| JPM 83    112  B   
1004| BP  74    166  S   
1005| JPM 87    136  B   
1006| BP  54    137  S   
1007| JPM 95    144  B   
1008| ASD 91    128  B   
1009| JPM 52    120  B   
1010| IBM 89    130  B   
1011| BP  81    111  B   
1012| JPM 65    156  B   
id  | sym price size side
----| -------------------
1001| IBM 79    117  B   
1002| GE  88    123  S   
1003| JPM 83    112  B   
1004| BP  74    166  S   
1005| JPM 87    136  B   
1006| BP  54    137  S   
1007| JPM 95    144  B   
1008| ASD 91    128  B   
1009| JPM 52    120  B   
1010| IBM 89    130  B   
1011| BP  81    111  B   
1012| JPM 65    156  B   
10 11
id  | sym price size side
----| -------------------
1001| IBM 79    117  B   
1002| GE  88    123  S   
1003| JPM 83    112  B   
1004| BP  74    166  S   
1005| JPM 87    136  B   
1006| BP  54    137  S   
1007| JPM 95    144  B   
1008| ASD 91    128  B   
1009| 

* Update the information for `tradeKey` id `1001` to the following:


    id   | sym   price   size     side
    -----| -----------------------------
    1001 | `BP    85      115     `B

In [ ]:
`tradeKey upsert(1001;`BP;85;115;`B)

In [126]:
tradeKey[1001]:`sym`price`size`side!(`BP;  85;  115; `B)
`tradeKey upsert (1001;`BP;85;115;`B)

tradeKey


## Functions

* Create a function `returnKeyedTable` which takes as input:<br> 


    - t  - table name (as symbol)
    - k - key(s) to key on

Returns the specified table keyed on k -  the underlying table should not be changed

Example of Code
    
    returnKeyedTable[`trade;`sym]                                        // returns a keys version of the table
    sym| time                          size price side exchange
    ---| ------------------------------------------------------
    GE | 2016.04.22D15:02:31.169380000 150  1025  B    N
    BP | 2016.04.22D15:02:31.169380000 210  1050  S    L

    trade                                                                // but doesn't alter the underlying table 
    time                          sym size price side exchange
    ----------------------------------------------------------
    2016.04.22D15:02:31.169380000 GE  150  1025  B    N
    2016.04.22D15:02:31.169380000 BP  210  1050  S    L

In [ ]:
returnKeyedTable:{[t;k]k xkey get t}

In [127]:
returnKeyedTable:{table: select from x; y xkey table}

Test your function using the code below

In [129]:
trade:flip`time`sym`size`prize`side`exchange!(2#2016.04.22D15:02:31.169380000;`GE`BP;150 210;1025 1050;`B`S;`N`L)
returnKeyedTable[`trade;`sym] 
trade

sym| time                          size prize side exchange
---| ------------------------------------------------------
GE | 2016.04.22D15:02:31.169380000 150  1025  B    N       
BP | 2016.04.22D15:02:31.169380000 210  1050  S    L       
time                          sym size prize side exchange
----------------------------------------------------------
2016.04.22D15:02:31.169380000 GE  150  1025  B    N       
2016.04.22D15:02:31.169380000 BP  210  1050  S    L       


* Create a function `applyKeyToTable` which takes as input:<br> 


    - t  - table name (as symbol)
    - k - key(s) to key on. If this list is empty, the table should be unkeyed

Returns the name of the table. The underlying table should be keyed / unkeyed as per the supplied argument

Example of Code
    
    applyKeyToTable[`trade;`sym]					          // alters the underlying table and just returns the table name
    `trade

    trade
    sym| time                          size price side exchange
    ---| ------------------------------------------------------
    GE | 2016.04.22D15:02:31.169380000 150  1025  B    N
    BP | 2016.04.22D15:02:31.169380000 210  1050  S    L

In [ ]:
applyKeyToTable:{[t;k]k xkey t}

In [144]:
applyKeyToTable:{y xkey x}
tab2:trade
get applyKeyToTable[`tab2;`sym]
get applyKeyToTable[`tab2;()]


sym| time                          size prize side exchange
---| ------------------------------------------------------
GE | 2016.04.22D15:02:31.169380000 150  1025  B    N       
BP | 2016.04.22D15:02:31.169380000 210  1050  S    L       
sym time                          size prize side exchange
----------------------------------------------------------
GE  2016.04.22D15:02:31.169380000 150  1025  B    N       
BP  2016.04.22D15:02:31.169380000 210  1050  S    L       


Test your function using the code below

In [145]:
applyKeyToTable[`trade;`sym] 
trade //should change

trade
sym| time                          size prize side exchange
---| ------------------------------------------------------
GE | 2016.04.22D15:02:31.169380000 150  1025  B    N       
BP | 2016.04.22D15:02:31.169380000 210  1050  S    L       


* For the next function, we will create a table `randomTable` with 20 rows and the following columns: 
     * sym - random selection from <code>\`AAPL\`MSFT\`FD\`KX</code>
     * time - random timestamp between midnight and the current time 
     * price - random decimal price between 20-40
     * qty - random quantity between 100-1000


In [ ]:
rows:20;
randomTable:([] sym: rows?`AAPL`MSFT`FD`KX;
                time: .z.d + rows?.z.t; 
                price: 20+rows?20f;
                qty:100+rows?901 )
randomTable

In [152]:
n:20
show randomTable:([] sym:n?`AAPL`MSFT`FD`KX; time:.z.d + n?.z.t; price:20+n?20f; qty:100+n?901)

sym  time                          price    qty
-----------------------------------------------
AAPL 2025.02.27D02:02:16.027000000 39.67777 511
AAPL 2025.02.27D04:18:39.298000000 31.14746 856
FD   2025.02.27D15:14:46.694000000 21.58361 197
KX   2025.02.27D05:24:21.691000000 28.81202 496
MSFT 2025.02.27D07:30:15.144000000 29.89813 488
AAPL 2025.02.27D10:30:25.569000000 26.76821 514
FD   2025.02.27D13:51:58.862000000 38.74355 948
MSFT 2025.02.27D18:34:50.225000000 24.3629  376
KX   2025.02.27D19:10:54.154000000 38.6665  996
FD   2025.02.27D19:02:17.036000000 39.93133 956
MSFT 2025.02.27D20:02:58.926000000 20.78783 361
KX   2025.02.27D07:53:09.750000000 30.19758 886
MSFT 2025.02.27D03:15:37.557000000 29.92655 415
KX   2025.02.27D18:14:27.656000000 36.77981 767
AAPL 2025.02.27D15:49:56.061000000 37.47702 455
KX   2025.02.27D15:34:39.159000000 29.53021 689
FD   2025.02.27D07:34:38.275000000 25.512   962
FD   2025.02.27D04:45:17.225000000 30.36307 863
KX   2025.02.27D14:22:48.154000000 27.45

* Create function `appendData` that takes as an input `randomTable`, either as a table value, or as a symbol and a list of data in dictionary format and returns randomTable with the data appended. Run the function with the following dictionary as input - <code>\`sym\`time\`price\`qty!(\`KX\`FD;2#.z.p;54.4 52.1;300 300)</code>. 

This should not affect the global randomTable. 

In [ ]:
randomTable
data:`sym`time`price`qty!(`KX`FD;2#.z.p;54.4 52.1;300 300)

In [ ]:
appendData:{[tab;dataDict] if[-11h~type tab;tab:get tab]; //if passed by reference (i.e. sym) get it's value
                    tab upsert flip dataDict}             //can't use insert, as we don't want to persist
//                  tab,flip dataDict}                    //could use this either

In [ ]:
appendData[`randomTable;data]
appendData[randomTable;data]

In [173]:
appendData:{
    tab:select from x;
    tab upsert flip y
 }
to_add:`sym`time`price`qty!(`KX`FD;2#.z.p;54.4 52.1;300 300)
appendData[randomTable;to_add] ~ tab:appendData[`randomTable;to_add]
-2#tab

1b
sym time                          price qty
-------------------------------------------
KX  2025.02.27D21:11:13.329039098 54.4  300
FD  2025.02.27D21:11:13.329039098 52.1  300


* Define the following two tables with the corresponding columns and types:

**trade**

* time (timestamp)
* sym (symbol)
* size (long)
* price (long)
* side (symbol)
* exchange (symbol)

**quote**

* time (timestamp)
* sym (symbol)
* bid (long)
* ask (long)
* bidSize (long)
* askSize (long)
* exchange (symbol)

Define a variable **BATCH** and assign it the value `1b` (true)

In [ ]:
trade:([]time:`timestamp$();sym:`$();size:`long$();price:`long$();side:`$();exchange:`$());
quote:([]time:`timestamp$();sym:`$();bid:`long$();ask:`long$();bidSize:`long$();askSize:`long$();exchange:`$());
BATCH:1b

In [236]:
trade:([] time:`timestamp$(); sym:`symbol$(); size:`long$(); price:`long$(); side:`symbol$(); exchange:`symbol$());
quote:([] time:`timestamp$(); sym:`symbol$(); bid:`long$(); ask:`long$(); bidSize:`long$(); askSize:`long$(); exchange:`symbol$());
BATCH:1b;
meta trade
meta quote

c       | t f a
--------| -----
time    | p    
sym     | s    
size    | j    
price   | j    
side    | s    
exchange| s    
c       | t f a
--------| -----
time    | p    
sym     | s    
bid     | j    
ask     | j    
bidSize | j    
askSize | j    
exchange| s    


* Create a function `upd` which takes as input:<br> 
    * t - the name of a table (a symbol) e.g. `trade` or `quote`
    * d - the data - this should  be a list, where each item in the list is an atom or list itself corresponding to the columns in the associated table (`trade` or `quote`)

**The function should (if BATCH is true):**
    - insert the data into the appropriate table
    - return the indices that the records were inserted at (e.g. 0 1 for the first 2 records inserted)

**The function should (if BATCH is false):**
    - not insert anything into the trade or quote tables
    - return a table populated with the data that was passed in

**If everything has been defined correctly, the following code snippets should all match examples**

Example of Code:

    BATCH:0b																// start by testing in non-batch mode
    upd[`trade;(2#.z.P;`ASD`IBM;300 400;4000 6000;`O`P;`N`D)]			   // test with two records
    time                          sym size price side exchange			  // copy of table returned
    ----------------------------------------------------------
    2016.03.19D12:17:50.871658000 ASD 300  4000  O    N
    2016.03.19D12:17:50.871658000 IBM 400  6000  P    D
    
    trade																    // underlying table should be unchanged
    time sym size price side exchange
    ---------------------------------

In [250]:
upd:{[t;d]$[BATCH;t insert d;get[t]upsert flip(),/:d]}

-12 -11 -7 -7 -7 -7 -11h
12 11 7 7 7 7 11h
2025.02.27D21:33:00.022836312 2025.02.27D21:33:00.022836312
ASD                           IBM                          
300                           400                          
4000                          6000                         
O                             P                            
N                             D                            


In [239]:
upd:{[tabname;data]
    if[BATCH;:tabname insert data];
    if[0>type first data;data:enlist each data];
    (get tabname) upsert flip data
 };

Test your function using the code below

In [240]:
BATCH:0b
trade
upd[`trade;(2#.z.P;`ASD`IBM;300 400;4000 6000;`O`P;`N`D)]  // test with two records
trade                                                      // underlying table should be unchanged

time sym size price side exchange
---------------------------------
time                          sym size price side exchange
----------------------------------------------------------
2025.02.27D21:31:24.406700671 ASD 300  4000  O    N       
2025.02.27D21:31:24.406700671 IBM 400  6000  P    D       
time sym size price side exchange
---------------------------------


In [241]:
BATCH:0b
quote
upd[`quote;(.z.P;`MSFT;745;755;100;200;`T)]                // should work with a single row also
quote  

time sym bid ask bidSize askSize exchange
-----------------------------------------
time                          sym  bid ask bidSize askSize exchange
-------------------------------------------------------------------
2025.02.27D21:31:26.641038613 MSFT 745 755 100     200     T       
time sym bid ask bidSize askSize exchange
-----------------------------------------


In [242]:
BATCH:1b                                                   // Batch mode on
upd[`quote;(.z.P;`APPL;15;20;190;650;`T)]                  // indices returned
quote  

,0
time                          sym  bid ask bidSize askSize exchange
-------------------------------------------------------------------
2025.02.27D21:31:29.165748159 APPL 15  20  190     650     T       


In [243]:
upd[`quote;(.z.P;`SHL;945;1055;200;250;`X)]
quote  

,1
time                          sym  bid ask  bidSize askSize exchange
--------------------------------------------------------------------
2025.02.27D21:31:29.165748159 APPL 15  20   190     650     T       
2025.02.27D21:31:31.187079501 SHL  945 1055 200     250     X       


In [244]:
upd[`trade;(2#.z.P;`ASD`IBM;300 400;4000 6000;`O`P;`N`D)]
trade

0 1
time                          sym size price side exchange
----------------------------------------------------------
2025.02.27D21:31:33.766117367 ASD 300  4000  O    N       
2025.02.27D21:31:33.766117367 IBM 400  6000  P    D       
